### ISSUE TITLE
Missing Directories

### ISSUE THREAD

**Issue by nmill22** [R-unic/WizWikiAPI#2]
Hello, I was curious about using this, and after a clone, I couldn't get the API to start up. I could reverse engineer all of this but I was hoping to have to do so. I am having an issue with the filepaths in the App.js file:

const docsHTML = readFileSync(__dirname + "/../docs/index.html", { encoding: "utf8" });
const docsHighlightCSS = readFileSync(__dirname + "/../docs/assets/highlight.css", { encoding: "utf8" });
const docsCSS = readFileSync(__dirname + "/../docs/assets/style.css", { encoding: "utf8" });
const mainJS = readFileSync(__dirname + "/../docs/assets/main.js", { encoding: "utf8" });
const searchJS = readFileSync(__dirname + "/../docs/assets/search.js", { encoding: "utf8" });
  
These are throwing the errors and the docs directory nor assets directory exists in the project. These just don't exist in the project and I was just wondering if this was supposed to be the case. I was going to use this to make a Discord bot, but I might just create my own scraper. If i could get some direction with this to get it up and running, I would like to finish it out per your readme. Let me know, thanks!

**Comment by R-unic** [comment]
You can start it using `npm start`.

My apologies for not including this in the README. Create a pull request if you'd like :)

**Comment by R-unic** [comment]
Okay so sorry for a year late response but: I misunderstood you. This repository is the API's server. This is not the repository you need to act as a library for your Discord bot. This repository hosts an API on the web. You're looking for [this repository](https://github.com/R-unic/Wizard101-API-TS-Wrapper).
